let X = 0,
  Y = 0,
  SCALE = 10,
  TIME = 0,
  PROPER_TIME = 0;
let VEL_X = 0, VEL_Y = 0;

let LIGHT_TRAVEL_TIME_DELAY = true;
let LIGHT_TRAVEL_TIME_DELAY_INCLUDES_SHIP_VELOCITY = true;
let SHIP_TIME_DIALATION = true;
let UNIVERSE_TIME_SHIFTING = true;
let UNIVERSE_LENGTH_CONTRACTION = true;
let ITEM_LENGTH_CONTRACTION = true;
let BLACK_BEFORE_UNIVERSE_START = true;
let SHIP_RELATIVISTIC_VELOCITY_ADDITION = true;
let RINDLER_METRIC_WHEN_ACCELERATING = false;
let RINDLER_METRIC_WHEN_ACCELERATING_TIMELIKE_VIEW = false;
let HIDE_RINDLER_METRIC_PAST_SINGULARITY = false;
let TIMELIKE_VIEW = false;
let TIMELIKE_VIEW_NORMALIZED_X_COORDINATE = false; // squish timelike view x coordinate so that light is a 45 degree diagonal
let MOUSEDRAG_RELATIVE_TO_FRAME = true;

let BACKGROUND_PULSE = true;
let SPEED_OF_LIGHT = 1;

let ACCEL = 1;
let TIME_RATE = 1;
let TIME_ADVANCING = false;

let SUBPIXEL_SCALE = 2;
